# Inserts a blank line between shell prompts
add_newline = false 

#The line_break module separates the prompt into two lines.
[line_break]
disabled = true 

# Replace the "❯" symbol in the prompt with "➜"
#[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = "🌱 "
truncation_length = 7
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"


[python]
symbol = "🐍"
disabled = false

#[shell]
#zsh_indicator = "🚀🚀"
#disabled = false 

#[hostname]
#ssh_only = false
#format =  "[$hostname](bold red) "
#trim_at = ".companyname.com"
#disabled = false

[directory]
truncation_length = 8
#truncation_symbol = "…/"

[docker_context]
format = "via [🐋 $context](blue bold)"

[cmd_duration]
min_time = 500
format = "⏳ [$duration](bold yellow)"
